version: '2'

services:
    http:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - http_proxy
                - https_proxy
                - RESOLVER=8.8.8.8
        ports:
            - "6006:8080"
        environment:
            - http_proxy
            - https_proxy

